# Generated by Django 5.0.9 on 2024-11-12 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadanalyticsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 16, 25, 22, 465466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=2871591322, null=True, unique=True),
        ),
    ]
