# Generated by Django 5.0.9 on 2024-09-26 19:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0002_alter_user_uid_alter_usertg_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadanalyticsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 22, 25, 56, 998031, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.clientbotuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=9179905208, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 26, 19, 25, 56, 995323, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
