# Generated by Django 5.0.9 on 2024-12-03 09:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0003_alter_downloadanalyticsmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadanalyticsmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=3923156118, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 3, 9, 6, 15, 330234, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
