# Generated by Django 5.0.9 on 2024-12-04 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0004_alter_downloadanalyticsmodel_date_alter_user_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=2684373300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 4, 16, 58, 33, 509203, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
